services:
  - type: web
    name: precios-unitarios-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
